version: "3.9"
services:
    phpunit:
        image: mobtitude/php-xdebug:7.4-cli
        entrypoint: [ "/usr/local/bin/php" ]
        command: [ "/app/vendor/bin/phpunit" ]
        working_dir: "/app"
        ports:
            - "9000:9000"
        user: "${DOCKER_USER}"
        volumes:
            - ./:/app
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
